--- #YAML:1.0
name:                POE-Component-Algorithm-Evolutionary
version:             0.0.4
abstract:            Run evolutionary algorithms in a preemptive multitasking way.
license:             ~
author:              
    - JJ Merelo <jj@merelo.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Algorithm::Evolutionary:       0.61
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
