--- #YAML:1.0
name:               POE-Component-Algorithm-Evolutionary
version:            0.2.0
abstract:           Run evolutionary algorithms in a preemptive multitasking way.
author:
    - JJ Merelo <jj@merelo.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Algorithm::Evolutionary:  0.64
    POE:                  0
    Test::More:           0
    Test::Output:         0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
