# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Algorithm-Evolutionary
version:      0.1.0
version_from: lib/POE/Component/Algorithm/Evolutionary.pm
installdirs:  site
requires:
    Algorithm::Evolutionary:       0.61
    POE:                           0
    Test::More:                    0
    Test::Output:                  0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
